### ISSUE TITLE
Redesign the logo to be pixel-perfect

### ISSUE THREAD

**Issue by trobonox** [trobonox/kanri#15]
Currently, the logo has been made by putting together two characters of a font and combining them in Figma. This approach creates some rough edges and would be prevented by a full redraw/redesign. If anyone wants to help out, please let me know!

Additionally, if you have suggestions for a new, better logo, you can also post your suggestions/concepts here!

**Comment by BhaveshDiwan** [comment]
I might be probably interested in helping here, however, cannot provide any commitment due to life circumstances. Please let me know if this is acceptable with an undefined timeline? Also want to ask if only the existing logo should be enhanced as-is, or alternate logo designs are also open for consideration?

**Comment by trobonox** [comment]
Thanks for showing interest into this issue.
An undefined timeline is perfectly fine, this issue has been open for a long time and there's no rush at all.
I'm definitely open for alternative logo design ideas, but just an improved version of the current logo would be totally fine too. Feel free to try out things as you please.

**Comment by trobonox** [comment]
I have come up with a new logo which will probably be released with the next big version 0.7, so this issue is not relevant anymore.
