### ISSUE TITLE
Data isn't saving when shutting down or restarting without closing the app first

### ISSUE THREAD

**Issue by Kra1ven** [trobonox/kanri#182]
After each restart, data is not saved. Exporting everything manually is a bit tedious and unusual (most people got used to spamming ctrl+s). Could you add auto save or a shortcut to export data?

**Comment by trobonox** [comment]
I'm sorry for this issue, usually all data should be persistent and auto-save on each action, so there should be no need for Ctrl + S or manual exports. 
Would you mind sharing some info like your app version (can be found in the help menu on the sidebar) and operating system?

The files should usually be saved in a JSON file, but maybe there's something wrong going on there... Maybe try doing a full reset in the app's settings and see if that changes anything?

**Comment by Kra1ven** [comment]
The version is v0.4.0, I'm on windows 10 22H2 (19045.2846) Pro.
Found out, that if I close the app normally, data is saved. But if I restart/shutdown without closing the app first, all data disappears.

**Comment by trobonox** [comment]
That's quite interesting, I am using Tauri's store plugin and it might only write data into the actual JSON as soon as the app is closed. This is out of my scope, the only solution for me to fix this would be to write some custom Rust logic to handle saving of data. 
Let me know if there's anything I can help you with, but for now I can't change a lot about the saving logic regarding this behaviour. 
I will add the idea of implementing custom Rust logic for data saves to the roadmap, but unfortunately because of personal reasons I'm unable to work on anything major for the app at the moment.

**Comment by Kra1ven** [comment]
> That's quite interesting, I am using Tauri's store plugin and it might only write data into the actual JSON as soon as the app is closed. This is out of my scope, the only solution for me to fix this would be to write some custom Rust logic to handle saving of data. Let me know if there's anything I can help you with, but for now I can't change a lot about the saving logic regarding this behaviour. I will add the idea of implementing custom Rust logic for data saves to the roadmap, but unfortunately because of personal reasons I'm unable to work on anything major for the app at the moment.

Ok, thanks for the answer. I just like this app, wouldn't want to swap because of a minor issue.

**Comment by trobonox** [comment]
Update: With the latest release, I have added logic which saves all data to the actual file after you close a board. This should mostly prevent data loss unless you're editing a board and shut down/restart while viewing the actual board.

Closing this for now, if there's anything else that doesn't behave like you'd expect feel free to open another issue.
