### ISSUE TITLE
Bug: Iconify icons don't load when offline

### ISSUE THREAD

**Issue by BhaveshDiwan** [trobonox/kanri#290]
On machines without internet access (or in my case where I use [lulu](https://github.com/objective-see/LuLu) to restrict applications from accessing internet) it is observed that Kanri doesn't load the icons and only placeholder text is shown. Once internet is restored then it downloads and caches the icons for some time.

Proposed solution is to bake icons during compile time.
<img width="1403" alt="Screenshot 2023-09-03 at 05 06 27" src="https://github.com/trobonox/kanri/assets/9309009/27baf6f6-e084-46e6-a348-9cf4ae1933fa">
<img width="1403" alt="Screenshot 2023-09-03 at 05 06 33" src="https://github.com/trobonox/kanri/assets/9309009/ee5852d5-c815-453a-8c96-7161f4300d6e">

**Comment by trobonox** [comment]
Thanks for pointing this out! I was not aware of this issue. Will look into what I can do to make the icons available offline.

**Comment by trobonox** [comment]
Added Phosphor Icons manually instead of relying on iconify. From what I've managed to pick up when building, the icons seem to be embedded in the build now, which should make them available offline!
Fix will be released with the next app release (will happen once some more features are done).

Closing this for now, feel free to reopen if the issue still persists after the new release has been published.
