### ISSUE TITLE
Add confirmation to delete column using keyboard shortcut

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#311]
There's no "Are you sure?" and the column and all cards are gone.
I think there is no undo yet as well?

**Comment by trobonox** [comment]
Clicking the "x" icons on columns and cards triggers this confirmation, so it would probably make sense to trigger the same for the keyboard shortcut too.
Also yes you are correct, there is no undo and other similar operations implemented yet since the technical implementation behind that is not trivial, especially integrating it in a way which does not make the architecture cluttered and inflexible.
