### ISSUE TITLE
Memory Leak on Startup

### ISSUE THREAD

**Issue by immijimmi** [trobonox/kanri#418]
![image](https://github.com/trobonox/kanri/assets/9651027/d35b37f0-e6a7-492b-b27e-5fa0b5491b84)

I've been using the app for a little while now, and initially had no issues of this kind with it.

Recently, it's begun to take multiple minutes to start up (or simply does not start up at all - the process will show up in Task Manager but no window appears, and after a short while terminates on its own) and when checking on the process in Task Manager it is using >20GB. It also appears to be using much more CPU than should be necessary, but that might be the garbage collection working overtime since there is a memory leak.

I'm running Windows 10, if that helps.
If there's any additional information I can provide to help debug this, please let me know.

**Comment by trobonox** [comment]
Thanks for your bug report.

This is a known bug and should be fixed with the next release. I am holding it back a little because it will be a breaking change and reset custom board backgrounds, so the fix will only be part of version 0.6.

Meanwhile, please refer to the guide in the docs to resolve the issue (this will also reset your custom board background images once):
https://www.kanriapp.com/reference/troubleshooting/#app-is-taking-a-lot-of-time-to-loadslowing-down-and-using-a-lot-of-ram

**Comment by trobonox** [comment]
Should be fixed with the latest release
