### ISSUE TITLE
Hotkeys conflict at main board view

### ISSUE THREAD

**Issue by Rostezkiy** [trobonox/kanri#523]
**Description**
Hotkeys conflict at main board view while using CTRL and arrows to change cursor position.

**Steps to reproduce**
1. Open active board with some columns created.
2. Click on 'Add card' at any column.
3. Type some text at title and use CTRL +  ← or → to move cursor around word.

**Expected behavior**
Cursor moves to the start or end of the word.

**Actual result**
Cursor does not move, text of card title disappears, changing current column selection.

**Video**
https://github.com/trobonox/kanri/assets/73363254/7f39f914-2799-482f-8930-cf1227a7f883

**Desktop**
 - OS: Windows 10
 - Version Kanri 0.6.1

**Comment by trobonox** [comment]
Thanks for pointing this out, I was not aware of this shortcut. Will try out other options for the shortcuts to resolve this conflict.

**Comment by trobonox** [comment]
Totally forgot to update on this issue:
It's fixed, I have added the alt key as an additional key that's needed to move around columns. Additionally, instead of just using the arrow keys you can also use H and L to move left and right, similar to vim motions. 
(So the new shortcuts are either `Ctrl/Meta` + `Alt` + `ArrowLeft/Right` or `Ctrl/Meta` + `Alt `+ `H/L`)

**Comment by trobonox** [comment]
Released with v0.7
