### ISSUE TITLE
Pasting a hex value into a color picker doesn't work.

### ISSUE THREAD

**Issue by ludrol** [trobonox/kanri#532]
**Describe the bug**

Pasting a hex value into a color picker doesn't work.

**To Reproduce**
1. copy a hexvalue into a clipboard 
2. highlight input field 
3. press ctrl+v

**Expected behavior**
pasted value
 
**Screenshots**
![2024-03-22 12_36_42-Greenshot](https://github.com/trobonox/kanri/assets/37674089/11561492-937c-46dc-b42a-9394558a71de)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version: Kanri v0.6.1

**Additional context**

**Comment by trobonox** [comment]
Thanks for reporting the issue. I am aware of it and I have found a way to fix this by allowing you to modify the color in the text field above the color picker (that color picker is the one coming from your system, in this case Windows, so I cannot modify it).

This change will be out with the next release (0.7), but please be patient because that is still a work in progress and it will probably take a while to be released.

**Comment by trobonox** [comment]
Added with release v0.7
