### ISSUE TITLE
Kanri freezes when clicking more options

### ISSUE THREAD

**Issue by Auerilas** [trobonox/kanri#541]
Hi,
Running fully updated Linux Mint Cinnamon.

Have a new issue where Kanri freezes whenever I click the three buttons to get more options. I'm trying to delete a board, click the three buttons, and the program hangs. Happens in the overall board view, and within a single board.

**Comment by trobonox** [comment]
Thanks for reporting this. It's a known issue with a dependency and I fixed it a few versions ago, but it seems like it's happening once again :/
I'll take a look if it's the same issue and see if I can fix it.

**Comment by trobonox** [comment]
Just checked the commit history a bit and I think I know what's going on. The dependency is related to the dropdown menus and it kept breaking, so in the beta version (which you are probably running since it fixes #535) I reverted it to an older version. Essentially, I fixed one issue and accidentally triggered an old one again :(

I think I will have to find a replacement for that library, but I am unable to work on Kanri for the next 1-2 weeks so I am very sorry for the inconvenience :/

The stable v0.6.1 shouldn't have this issue if my theory is correct, so maybe try using that in the meantime. (If you need the imports on 0.6.1, a workaround is to create a custom theme on the device where you're taking your data from, save it and then make your full export; you should be able to import it without any errors)

**Comment by Auerilas** [comment]
I believe I am using 0.6.1, so I wonder if the issue is related to an
update to a dependency on linux.

**Comment by trobonox** [comment]
strange... maybe it's another linux issue
will definitely have to find a replacement for that dependency either way and will let you know once that's done

**Comment by trobonox** [comment]
Update: I have replaced all old dropdown menus with a new library which should hopefully not be as broken. Do you still have this issue? If so, I can make another Linux build in the next few days and publish it in the previews Discord channel.

**Comment by trobonox** [comment]
Fixed with release v0.7
