### ISSUE TITLE
[BUG] Cannot enter text when meta-key is pressed

### ISSUE THREAD

**Issue by manuel-mauky** [trobonox/kanri#75]
**Describe the bug**
I'm using a US-layout keyboard but sometimes have to write german umlauts. For this I'm using a key-mapping so that when I press Meta-Key (Windows-Key on Windows) + `u` I get `ü`, `meta`+`a` --> `ä`... 
This works in all other applications without issues but it doesn't work in kanri.
When I try to enter text in one of the text fields (e.g. adding a new task), as soon as I press meta+u it closes the textfield.
It seems as if your app is listening for the meta-key or something like that?

I think the root issue may be that the textfields are closed as soon as you unfocus the textfield. In my oppinion this is bad usability as it also makes things like copy-pasting text harder. There is the cancel button in case you want to abort entering some text. I think it would be better to remove this close-on-unfocus-functionality altogether.

**To Reproduce**
1. In a board, click on "+ Add card"
2. Enter some text
3. click outside the textfield
4. Textfield is closed and entered text is gone

**Expected behavior**
Textfield stays open and the entered text stays there.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version: v0.3.0

**Comment by trobonox** [comment]
Thank you for your bug report. 

If you believe your issue is related to the input closing when it loses focus, I will fix that with the next release. I understand why this kind of behaviour can be a problem and it was mostly a leftover from other inputs.
Small question from me here: Should the user have full control over all column inputs, or should the app only allow one column to have an opened input at a time? It's a minor thing but I'm not sure how to go about it.

I have also tried to include some additional checks in my keyboard shortcut handler, but my current implementation in general is not optimal so it might be fundamentally flawed.

I will publish my current fix as a new patch release in a bit, so please try downloading that new release when it is out and let me know if the issue persists. Happy to assist if you have any further issues.

**Comment by trobonox** [comment]
Note that this fix only applies for the input to create a new card since the ones for editing column and board titles don't have a cancel button to close them

**Comment by manuel-mauky** [comment]
Thank for the fast response. I've tested the update and it fixes my issue with the keyboard. Thanks!
It also works for the edit column textfield.

**Comment by trobonox** [comment]
Great, I'll be closing this then. Thanks again for your report and if there's anything else you can open another issue anytime. 👍
